executable = ./createOrbitDB_CNAF.sh
arguments = ""
log = ./createOrbitDB.log
output = ./createOrbitDB.out
error = ./createOrbitDB.err
transfer_input_files = ./createOrbitDB_CNAF.py
transfer_output_files = CSES01_orbitdb.h5

#+JobFlavour = "tomorrow"
+JobFlavour = "espresso"
on_exit_remove = (ExitBySignal == False) && (ExitCode == 0) || (ExitCode == 11)
max_retries = 5
requirements = Machine =!= LastRemoteHost


queue 1
